# frozen_string_literal: true

RSpec.shared_context 'collections' do
  let(:users) do
    [{ id: 4,
       first_name: 'Charlette',
       last_name: 'Johnson',
       roles: [{ id: 1, name: 'admin', description: 'Superuser.' }],
       email: 'charlette-johnson@example.com',
       posts: [{ id: 1,
                 title: 'Vero.',
                 body: 'Autem consequatur sed. Labore et nam. Asperiores velit quis.',
                 user_id: 4,
                 tag_names: 'dolores,magnam,et',
                 comments: [{ id: 1,
                              user_id: 3,
                              body: 'Ut et quisquam. Qui ea omnis. Atque et facilis.',
                              post_id: 1 }] },
               { id: 2,
                 title: 'Et.',
                 body: 'Culpa qui dignissimos. Consequatur animi aliquam. Neque odit ea.',
                 user_id: 4,
                 tag_names: 'ut,et,tempora',
                 comments: [{ id: 2,
                              user_id: 3,
                              body: 'Et ea quae. Dolorem blanditiis autem. A et temporibus.',
                              post_id: 2 },
                            { id: 3,
                              user_id: 2,
                              body: 'Rerum quae unde. Laudantium voluptatibus quam. Voluptatum facere alias.',
                              post_id: 2 },
                            { id: 4,
                              user_id: 1,
                              body: 'Asperiores quisquam enim. Consequuntur ullam error. Sint error sit.',
                              post_id: 2 }] }],
       created_at: Time.parse('2024-07-18 08:13:10 +0500'),
       updated_at: Time.parse('2024-07-23 17:10:10 +0500') },
     { id: 5,
       first_name: 'Gaston',
       last_name: 'Bednar',
       roles: [{ id: 1, name: 'admin', description: 'Superuser.' }],
       email: 'gaston-bednar@example.com',
       posts: [{ id: 3,
                 title: 'Voluptatem.',
                 body: 'Ut et aut. Accusamus incidunt facere. Et et fuga.',
                 user_id: 5,
                 tag_names: 'et,voluptas,necessitatibus',
                 comments: [{ id: 5,
                              user_id: 3,
                              body: 'Sequi et repudiandae. Reprehenderit odit sed. Eaque maxime tempora.',
                              post_id: 3 }] },
               { id: 4,
                 title: 'Provident.',
                 body: 'Exercitationem accusantium et. Optio quam soluta. Porro animi voluptate.',
                 user_id: 5,
                 tag_names: 'minus,qui,porro',
                 comments: [{ id: 6,
                              user_id: 1,
                              body: 'Itaque sint ea. Blanditiis autem quia. Fugiat maiores ad.',
                              post_id: 4 }] },
               { id: 5,
                 title: 'Voluptatem.',
                 body: 'Et et architecto. Minus corporis officia. Possimus et suscipit.',
                 user_id: 5,
                 tag_names: 'neque,enim,consequatur',
                 comments: [{ id: 7,
                              user_id: 3,
                              body: 'Beatae maxime nisi. Qui dicta non. Laborum id sunt.',
                              post_id: 5 }] }],
       created_at: Time.parse('2024-06-02 19:45:10 +0500'),
       updated_at: Time.parse('2024-06-07 16:59:10 +0500') },
     { id: 6,
       first_name: 'Stan',
       last_name: 'Rau',
       roles: [{ id: 1, name: 'admin', description: 'Superuser.' }],
       email: 'stan-rau@example.com',
       posts: [],
       created_at: Time.parse('2024-06-25 02:13:10 +0500'),
       updated_at: Time.parse('2024-06-26 20:13:10 +0500') },
     { id: 7,
       first_name: 'Betty',
       last_name: 'Gorczany',
       roles: [{ id: 1, name: 'admin', description: 'Superuser.' }],
       email: 'betty-gorczany@example.com',
       posts: [{ id: 6,
                 title: 'Ratione.',
                 body: 'Error nobis placeat. Et hic ut. Vel vel aut.',
                 user_id: 7,
                 tag_names: 'architecto,eaque,qui',
                 comments: [{ id: 8,
                              user_id: 3,
                              body: 'Sed distinctio voluptatum. Consectetur dolores minus. Veniam explicabo et.',
                              post_id: 6 }] },
               { id: 7,
                 title: 'Quas.',
                 body: 'Repellat id aut. Neque debitis blanditiis. Quis dolores ab.',
                 user_id: 7,
                 tag_names: 'aperiam,necessitatibus,et',
                 comments: [{ id: 9,
                              user_id: 1,
                              body: 'Cum voluptatum mollitia. Enim veniam molestiae. Quod mollitia eos.',
                              post_id: 7 },
                            { id: 10,
                              user_id: 1,
                              body: 'Culpa corporis quo. Modi ipsa delectus. Inventore et ut.',
                              post_id: 7 },
                            { id: 11,
                              user_id: 2,
                              body: 'Recusandae nisi quia. Quae vero esse. Similique facere mollitia.',
                              post_id: 7 }] },
               { id: 8,
                 title: 'Id.',
                 body: 'Rerum distinctio sed. Blanditiis ea sunt. Doloribus doloremque error.',
                 user_id: 7,
                 tag_names: 'cumque,est,vitae',
                 comments: [{ id: 12,
                              user_id: 1,
                              body: 'Voluptatem alias quia. Quos sed et. Suscipit velit dolore.',
                              post_id: 8 }] }],
       created_at: Time.parse('2024-08-01 22:19:10 +0500'),
       updated_at: Time.parse('2024-08-03 20:57:10 +0500') },
     { id: 8,
       first_name: 'Winston',
       last_name: 'Bogisich',
       roles: [{ id: 1, name: 'admin', description: 'Superuser.' }],
       email: 'winston-bogisich@example.com',
       posts: [{ id: 9,
                 title: 'Quia.',
                 body: 'Eum est voluptate. Non nesciunt animi. Ipsam porro commodi.',
                 user_id: 8,
                 tag_names: 'necessitatibus,animi,non',
                 comments: [{ id: 13,
                              user_id: 3,
                              body: 'Ullam odio aspernatur. Ad dolores et. Nobis magni et.',
                              post_id: 9 }] },
               { id: 10,
                 title: 'Itaque.',
                 body: 'Quisquam sint voluptates. Placeat quas est. Est fugit nesciunt.',
                 user_id: 8,
                 tag_names: 'quis,sapiente,iste',
                 comments: [{ id: 14,
                              user_id: 1,
                              body: 'Voluptates molestiae occaecati. Quia beatae aut. Officia corrupti ipsam.',
                              post_id: 10 },
                            { id: 15,
                              user_id: 1,
                              body: 'Id impedit qui. Minus tempore inventore. Consequatur sequi aut.',
                              post_id: 10 },
                            { id: 16,
                              user_id: 2,
                              body: 'Deleniti enim et. Veritatis et maxime. Labore magnam sint.',
                              post_id: 10 }] }],
       created_at: Time.parse('2024-06-19 22:05:10 +0500'),
       updated_at: Time.parse('2024-06-22 09:15:10 +0500') },
     { id: 9,
       first_name: 'Jerica',
       last_name: 'Witting',
       roles: [{ id: 1, name: 'admin', description: 'Superuser.' }],
       email: 'jerica-witting@example.com',
       posts: [],
       created_at: Time.parse('2024-06-03 02:49:10 +0500'),
       updated_at: Time.parse('2024-06-03 16:07:10 +0500') },
     { id: 10,
       first_name: 'Philip',
       last_name: 'Pagac',
       roles: [{ id: 1, name: 'admin', description: 'Superuser.' }],
       email: 'philip-pagac@example.com',
       posts: [],
       created_at: Time.parse('2024-06-03 18:39:10 +0500'),
       updated_at: Time.parse('2024-06-04 23:36:10 +0500') },
     { id: 11,
       first_name: 'Rolland',
       last_name: 'Renner',
       roles: [{ id: 1, name: 'admin', description: 'Superuser.' }],
       email: 'rolland-renner@example.com',
       posts: [{ id: 11,
                 title: 'Nihil.',
                 body: 'Maxime aliquam quas. Vel a ex. Dignissimos sint ut.',
                 user_id: 11,
                 tag_names: 'ratione,corporis,necessitatibus',
                 comments: [{ id: 17,
                              user_id: 2,
                              body: 'Necessitatibus architecto modi. Ad ipsum asperiores. Cum quisquam accusantium.',
                              post_id: 11 },
                            { id: 18,
                              user_id: 3,
                              body: 'Delectus facere fugit. Iure vel incidunt. Sit nihil perferendis.',
                              post_id: 11 },
                            { id: 19,
                              user_id: 3,
                              body: 'Soluta odit quis. Qui et aliquid. Ducimus deleniti est.',
                              post_id: 11 }] },
               { id: 12,
                 title: 'At.',
                 body: 'Quasi quia ab. Officia nemo harum. Pariatur sapiente nulla.',
                 user_id: 11,
                 tag_names: 'veritatis,id,in',
                 comments: [] }],
       created_at: Time.parse('2024-08-06 04:46:10 +0500'),
       updated_at: Time.parse('2024-08-06 22:28:10 +0500') },
     { id: 12,
       first_name: 'Anglea',
       last_name: 'Abbott',
       roles: [{ id: 1, name: 'admin', description: 'Superuser.' }],
       email: 'anglea-abbott@example.com',
       posts: [{ id: 13,
                 title: 'Voluptatem.',
                 body: 'Repudiandae voluptates voluptatum. Ipsa ullam provident. Voluptas accusantium aut.',
                 user_id: 12,
                 tag_names: 'provident,et,quis',
                 comments: [{ id: 20,
                              user_id: 2,
                              body: 'Eos porro odio. Rem corporis consequatur. Autem enim quis.',
                              post_id: 13 }] },
               { id: 14,
                 title: 'Architecto.',
                 body: 'Ut ea sapiente. Eligendi quas vero. Tempore fugiat esse.',
                 user_id: 12,
                 tag_names: 'ullam,est,totam',
                 comments: [] }],
       created_at: Time.parse('2024-08-02 22:48:10 +0500'),
       updated_at: Time.parse('2024-08-06 15:10:10 +0500') },
     { id: 13,
       first_name: 'Valentina',
       last_name: 'Lockman',
       roles: [{ id: 1, name: 'admin', description: 'Superuser.' }],
       email: 'valentina-lockman@example.com',
       posts: [],
       created_at: Time.parse('2024-06-11 21:00:10 +0500'),
       updated_at: Time.parse('2024-06-18 12:11:10 +0500') }]
  end
end
